### ISSUE TITLE
Example required

### ISSUE THREAD

**Issue by sumukhj84** [expandjs/xp-i18n-behavior#1]
Hi Giuliano Rullo,

I would like to use this behavior in my project. Do you have any example for it.
If yes then it will be great if you can share it.
From document it seems to be promising to use the behavior approach.

Thanks,
Sumukh

**Comment by Pupix** [comment]
Hello!

You can find an example usage in the [starter-kit](https://github.com/ExpandJSLabs/app-starter-kit/blob/master/app/elements/app-shell.html#L87) from ExpandJSLabs. You need to create a localization schema file with `xp-meta` and path set to `locale.LANGUAGE`, as seen [here](https://github.com/ExpandJSLabs/app-starter-kit/blob/master/app/elements/app-locale-en.html#L3).

To select which `LANGUAGE` to use, your app's shell must either have [xp-shell-behavior](https://github.com/expandjs/xp-shell-behavior/blob/master/xp-shell-behavior.html) and [bind language](https://github.com/ExpandJSLabs/app-starter-kit/blob/master/app/elements/app-shell.html#L172) or manually `share` the current language like [here](https://github.com/expandjs/xp-shell-behavior/blob/master/xp-shell-behavior.html#L58).

If you have any other questions let me know.
Cheers.

**Comment by sumukhj84** [comment]
Thanks Pupix for your help.
